spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=evdealer1;encrypt=false
    username: sa
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          time_zone: UTC
  jackson:
    time-zone: Asia/Ho_Chi_Minh

# Cấu hình VNPAY
vnpay:
  tmnCode: 81KUS46F
  hashSecret: WU7YVUBHETLQKAQU9HIXEQIPVBOTFAGN
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: www.google.com
  ipnUrl: https://your-public-domain.com/api/payments/vnpay/ipn
  currCode: VND
  locale: vn
  orderType: other

server:
  port: 8080
